// Claude Code strips block-level HTML comments from a CLAUDE.md file before it injects the
// content, and keeps a comment inside a code block
// (https://code.claude.com/docs/en/memory#how-claude-md-files-load). Text that reads as an
// instruction inside such a comment never reaches Claude. The rule reports a block comment with an
// all-caps modal word, an imperative at the start of a sentence, or an `@path`. The globs are in
// tests/configs.test.ts.
import { describe, expect, it } from 'vitest'
import { lintMarkdown } from '../rule-tester.test-support.ts'

const RULE = 'claude-md-html-comment-content'

/** The messages for `code` as the file `file`. */
function lint(code: string, file = '/repo/CLAUDE.md') {
  return lintMarkdown(RULE, code, file)
}

const ids = (messages: { messageId?: string | null }[]) => messages.map((m) => m.messageId)

describe(RULE, () => {
  it.fails('reports a block comment with a modal word in capitals, over the whole comment', () => {
    const messages = lint('# Notes\n\n<!-- MUST run tests -->\n')
    expect(messages).toHaveLength(1)
    expect(messages[0]).toMatchObject({
      ruleId: `claude/${RULE}`,
      messageId: 'instruction',
      line: 3,
      column: 1,
      endLine: 3,
      endColumn: 25,
    })
    expect(messages[0]?.message).toContain('`MUST`')
  })

  it.fails('reports each word of the list, and a comment of several lines, once', () => {
    for (const word of ['MUST', 'NEVER', 'ALWAYS', 'IMPORTANT', 'SHALL', 'REQUIRED']) {
      expect(ids(lint(`<!-- ${word} do it -->\n`)), word).toEqual(['instruction'])
    }
    const messages = lint('<!--\nFirst line.\nMUST run tests. NEVER skip.\n-->\n')
    expect(messages.map((m) => [m.line, m.endLine])).toEqual([[1, 4]])
    expect(messages[0]?.message).toContain('`MUST`')
  })

  it.fails('reports an imperative at the start of the comment or of a sentence', () => {
    for (const text of [
      'Always use pnpm',
      'Never commit secrets',
      "Don't edit this file",
      'Do not edit this file',
      'Use the strict config',
      'Run the tests first',
      'Prefer small commits',
      'Avoid globals',
      'Ensure the build passes',
      'Make sure the build passes',
      'Follow the style guide',
      'Note this. Never commit secrets',
      'Note this!\n  Run the tests',
    ]) {
      expect(ids(lint(`<!-- ${text} -->\n`)), text).toEqual(['instruction'])
    }
    expect(lint('<!-- Never commit -->\n')[0]?.message).toContain('`Never`')
  })

  it.fails('reports an @path that has a slash or a dot', () => {
    expect(ids(lint('<!-- see @docs/a.md -->\n'))).toEqual(['instruction'])
    expect(ids(lint('<!-- @README.md -->\n'))).toEqual(['instruction'])
    expect(lint('<!-- see @docs/a.md -->\n')[0]?.message).toContain('`@docs/a.md`')
  })

  it.fails('stays silent on a note for maintainers', () => {
    for (const text of [
      'maintainer: jo',
      'TODO update this in 2027',
      'this must be reviewed each year',
      'we use pnpm and run tests',
      'Used by the build',
      'Runner notes',
      'ping @alice about it',
      '',
    ]) {
      expect(lint(`<!-- ${text} -->\n`), text).toEqual([])
    }
  })
})

describe(`${RULE}: which comments`, () => {
  it.fails('reports a block comment in a list item or a quote', () => {
    expect(ids(lint('- item\n\n  <!-- MUST run tests -->\n'))).toEqual(['instruction'])
    expect(ids(lint('> <!-- MUST run tests -->\n'))).toEqual(['instruction'])
  })

  it.fails('reports a comment that is never closed, which runs to the end of the file', () => {
    expect(ids(lint('<!-- MUST run tests\n'))).toEqual(['instruction'])
  })

  it.fails('stays silent on an inline comment, which is part of a paragraph', () => {
    expect(lint('Text <!-- MUST run tests --> more text.\n')).toEqual([])
    expect(lint('- item <!-- MUST run tests -->\n')).toEqual([])
  })

  it.fails('stays silent on a comment in a code span, a fence or an indented block', () => {
    expect(lint('Write `<!-- MUST run tests -->` here.\n')).toEqual([])
    expect(lint('```html\n<!-- MUST run tests -->\n```\n')).toEqual([])
    expect(lint('~~~\n<!-- MUST run tests -->\n~~~\n')).toEqual([])
    expect(lint('Example:\n\n    <!-- MUST run tests -->\n')).toEqual([])
  })

  it.fails('stays silent on a comment inside another HTML block', () => {
    expect(lint('<div>\n<!-- MUST run tests -->\n</div>\n')).toEqual([])
  })

  it.fails('reports each of two comments', () => {
    const messages = lint('<!-- MUST run tests -->\n\ntext\n\n<!-- NEVER skip -->\n')
    expect(messages.map((m) => m.line)).toEqual([1, 5])
  })

  it.fails('reads a comment after other blocks, with frontmatter above it', () => {
    expect(ids(lint('---\nname: x\n---\n\n<!-- MUST run tests -->\n'))).toEqual(['instruction'])
  })
})

describe(`${RULE}: which files`, () => {
  it.fails('checks a CLAUDE.md and a CLAUDE.local.md, in any folder', () => {
    for (const file of [
      '/repo/CLAUDE.md',
      '/repo/.claude/CLAUDE.md',
      '/repo/CLAUDE.local.md',
      '/repo/packages/web/CLAUDE.md',
    ]) {
      expect(ids(lint('<!-- MUST run tests -->\n', file)), file).toEqual(['instruction'])
    }
  })

  it.fails('does not check a file that the docs do not name for this strip', () => {
    for (const file of [
      '/repo/AGENTS.md',
      '/repo/.claude/rules/CLAUDE.md',
      '/repo/.claude/rules/style.md',
      '/repo/docs/notes.md',
      '/repo/claude.md',
    ]) {
      expect(lint('<!-- MUST run tests -->\n', file), file).toEqual([])
    }
  })
})
